---
filter:
    excluded_paths: [vendor/, bin/, tests/]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 1200
    sensiolabs_security_checker: true
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, bin, tests]
    php_pdepend:
        excluded_dirs: [vendor, bin, tests]
